### PR TITLE
Adds support for multi-user authentication

### PR DESCRIPTION
**Pull request by JosephSalisbury**
Towards https://github.com/giantswarm/prometheus-pingdom-exporter/issues/9

If the --account-email flag is specified, we use the multi user
authentication client, instead of the default client.

### CODE REVIEW

**Comment by JosephSalisbury** [comment]
@rosscdh i've pushed the image:
```
giantswarm/prometheus-pindom-exporter:multi-user-authentication-test-1
```
which is based off this PR.

Would you mind doing a little testing for me? We don't use the multi-user authentication features of pindom, so it's a little difficult for me.

Usage:
```
joseph on dev-workspace-dc87n at 12:21:13 in /home/joseph
$ docker run giantswarm/prometheus-pindom-exporter:multi-user-authentication-test-1 server --help
Start the HTTP server

Usage:
  prometheus-pingdom-exporter server [username] [password] [api-key] [flags]

Flags:
      --account-email string   account email for multi-user authentication
      --port int               port to listen on (default 8000)
      --wait int               time (in seconds) between accessing the Pingdom  API (default 10)
```

So, you should only need to specify `--acount-email`, and with any luck, it'll work! :D

If that all works, I'll merge this in, make a new release.

**Comment by rosscdh** [comment]
+1 seems to be working. Great work!! and fast! I'll test the integration and give feedback here?

**Comment by JosephSalisbury** [comment]
No worries - you got me on a lazy saturday :D

Post any feedback you have here, awesome.

**Comment by rosscdh** [comment]
100% working and more than decent thanks for amazing fast response!

**Comment by rosscdh** [comment]
However, after some hours I get segfaults

```
docker run -p 8000:8000 giantswarm/prometheus-pindom-exporter:multi-user-authentication-test-1 server r.crawford@somewhere.de Test2007 n2hhtq03ruyqbnksasozev1ycg7fz57y --account-email r.crawford@somewhere.de
```

```
 Listening on port 8000
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x5350a8]

goroutine 11 [running]:
panic(0x779b20, 0xc420012020)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/russellcardullo/go-pingdom/pingdom.(*CheckService).List(0xc4200200a8, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/code/.gobuild/src/github.com/russellcardullo/go-pingdom/pingdom/check.go:32 +0x108
github.com/giantswarm/prometheus-pingdom-exporter/cmd.serverRun.func1(0xc420046960)
	/usr/code/.gobuild/src/github.com/giantswarm/prometheus-pingdom-exporter/cmd/server.go:90 +0x65
created by github.com/giantswarm/prometheus-pingdom-exporter/cmd.serverRun
	/usr/code/.gobuild/src/github.com/giantswarm/prometheus-pingdom-exporter/cmd/server.go:147 +0xf8
```

**Pull request closed without merging**
