### PR TITLE
Adds vendoring

### PR DESCRIPTION
**Pull request by JosephSalisbury**
Towards https://github.com/giantswarm/prometheus-pingdom-exporter/issues/11

### CODE REVIEW

**Comment by JosephSalisbury** [comment]
@boughtonp we're not reallllly using this project anymore, but I think I might have a solve for you.

This PR updates the vendoring, so the project builds correctly.
Using the following against this branch:
```
docker run --rm -v $(PWD):/go/src/github.com/giantswarm/prometheus-pingdom-exporter -w /go/src/github.com/giantswarm/prometheus-pingdom-exporter -e GOOS=windows golang:1.9.1 go build
```
(so you only need Docker installed, as opposed to a full golang installation)
gives me 
```
$ file ./prometheus-pingdom-exporter.exe
./prometheus-pingdom-exporter.exe: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows
```
which looks correct. i don't have a windows environment handy, so I can't check for you further. Does this help?

**Comment by boughtonp** [comment]
Thanks Joseph. Unfortunately Docker requires Windows 10.

Does Travis export executable snapshots anywhere?

**Comment by JosephSalisbury** [comment]
Not right now. Can you install a golang toolchain?

**Comment by boughtonp** [comment]
Ok, so I installed Go and the following in Git Bash has given me an EXE:

```
git clone https://github.com/giantswarm/prometheus-pingdom-exporter.git
cd prometheus-pingdom-exporter
/c/Golang/bin/go get github.com/giantswarm/prometheus-pingdom-exporter/cmd
/c/Golang/bin/go build
```

Then running `./prometheus-pingdom-exporter server.exe <USERNAME> <PASSWORD> <API-KEY>` gives what looks like correct data at `http://localhost:8000/metrics` - I'll check it properly on the Prometheus server tomorrow.

Thanks. :)

**Comment by JosephSalisbury** [comment]
@boughtonp any news?

**Comment by JosephSalisbury** [comment]
I'm gonna merge anyway, close this PR out, in case anyone else needs the code.

**Comment by boughtonp** [comment]
Sorry for not getting back, but yes we've had this running on Prometheus and it's working.


Well, we do occasionally get the down value stuck after a check has recovered (possibly this is issue #3 not sure). Restarting the exporter solves it and so far it's not a big enough issue to do more than that.

**Pull request merged**
